#!/bin/bash

#by Pascal3366

clear

ssh=""
internet=""
root_part=""
efi_boot_part=""
bios_boot_part=""
home_part=""
swap_part=""

echo "Welcome to the Easy Gentoo Installer!"
echo "brought to you by Pascal3366"
echo "this is free software lying under the GPLv3"
echo "feel free to fork, share or contribute!"
echo "This script needs to be run under root."
echo "------------------------------------"
echo "Getting IP address through DHCP..."
dhcpcd
echo "Testing Internet Access ..."
ping -c 3 www.gentoo.org
echo "Does the Internet Access work? (yes/no)"
read internet

if [ "$internet" = "no" ]
then
    net-setup eth0
else
    echo ""
fi

echo "Would you like to start an SSH-Server for remote installation? (yes/no)"
read ssh

if [ "$ssh" = "yes" ]
then
    /etc/init.d/sshd start
else
    echo ""
fi

    echo "Partitioning"
    echo "(Please input just the block device without /dev/)"
    echo "------------------------------------"
    echo "Choose the block device for the root partition:"
    lsblk
    echo "Input:"
    read root_part
    mkfs.ext4 /dev/$root_part
    echo "Choose the block device for the efi boot partition:"
    lsblk
    echo "Input:"
    read boot_part
    mkfs.vfat /dev/$efi_boot_part
    echo "Choose the block device for the BIOS boot partition:"
    lsblk
    echo "Input:"
    read bios_boot_part
    mkfs.ext2 /dev/$bios_boot_part
    echo "Choose the block device for the home partition:"
    lsblk
    echo "Input:"
    read home_part
    mkfs.ext4 /dev/$home_part
    echo "Choose the block device for the swap partition:"
    lsblk
    echo "Input:"
    read swap_part
    mkswap /dev/$swap_part
    swapon /dev/$swap_part
    echo "Mounting the partitions..."
    mount /dev/$root_part /mnt/gentoo
    mkdir /mnt/gentoo/boot
    mkdir /mnt/gentoo/boot/efi
    mkdir /mnt/gentoo/home
    mount /dev/$efi_boot_part /mnt/gentoo/boot/efi
    mount /dev/$bios_boot_part /mnt/gentoo/boot
    mount /dev/$home_part /mnt/gentoo/home
    echo "Getting the newest stage3 tarball..."
    cd /mnt/gentoo
    wget http://ftp.halifax.rwth-aachen.de/gentoo/releases/amd64/autobuilds/current-stage3-amd64/stage3-amd64-20160526.tar.bz2
    tar xvjpf stage3-*.tar.bz2 --xattrs
    read -p "Press any key to edit your make.conf" -n1 -s
    nano -w /mnt/gentoo/etc/portage/make.conf
    echo "Selecting the best mirror..."
    mirrorselect -i -o >> /mnt/gentoo/etc/portage/make.conf
    echo "Creating portage repos ..."
    mkdir /mnt/gentoo/etc/portage/repos.conf
    cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
    echo "saving DNS Info to installation"
    cp -L /etc/resolv.conf /mnt/gentoo/etc/
    echo "Mounting all neccessary filesystems for chrooting ..."
    mount -t proc proc /mnt/gentoo/proc
    mount --rbind /sys /mnt/gentoo/sys
    mount --make-rslave /mnt/gentoo/sys
    mount --rbind /dev /mnt/gentoo/dev
    mount --make-rslave /mnt/gentoo/dev
    echo "Getting into the new created chroot ..."
    wget https://raw.githubusercontent.com/Pascal3366/EasyGentoo/master/chrooted
    chmod a+x ./chrooted
    chroot /mnt/gentoo ./chrooted
